apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
