apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    labels:
        app: postgres
type: Opaque
data:
    POSTGRES_DB: cG9zdGdyZXMK
    POSTGRES_USER: cG9zdGdyZXMK
    POSTGRES_PASSWORD: cXdlcnR5Cg==
