apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    labels:
        app: postgres
type: Opaque
data:
    PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29tCg==
    PGADMIN_DEFAULT_PASSWORD: cXdlcnR5Cg==
    PGADMIN_PORT: ODAK
