Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    config.ssh.forward_agent = true
    
    config.vm.define "ubuntu1" do |ubuntu1|
      ubuntu1.vm.box = "ubuntu/trusty64"
      ubuntu1.vm.hostname = "ubuntu1"
      ubuntu1.vm.network "private_network", ip: "192.168.33.1"
    end
    
    config.vm.define "ubuntu2" do |ubuntu2|
      ubuntu2.vm.box = "ubuntu/trusty64"
      ubuntu2.vm.hostname = "ubuntu2"
      ubuntu2.vm.network "private_network", ip: "192.168.33.2"
    end

    config.vm.define "centos1" do |centos1|
        centos1.vm.box = "geerlingguy/centos7"
        centos1.vm.hostname = "centos1"
        centos1.vm.network "private_network", ip: "192.168.33.3"
    end

    config.vm.define "centos2" do |centos2|
        centos2.vm.box = "geerlingguy/centos7"
        centos2.vm.hostname = "centos2"
        centos2.vm.network "private_network", ip: "192.168.33.4"
    end

    config.vm.define "centos3" do |centos3|
        centos3.vm.box = "geerlingguy/centos7"
        centos3.vm.hostname = "centos3"
        centos3.vm.network "private_network", ip: "192.168.33.5"
    end
end